# Generated by Django 3.0.8 on 2020-07-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200725_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_pics/placeholder.png', null=True, upload_to='product_pics'),
        ),
    ]
